### ISSUE TITLE
从KeYi换回purpur后玩家存档丢失 (多世界插件)

### ISSUE THREAD

**Issue by ApliNi** [KeYiMC/KeYi#6]
Edit: purpur和KeYi服务器版本: 最新的 1.19.2

重现步骤: 

这个重现步骤不对. 

1. ~~安装purpur服务器~~
2. ~~安装 [MyWorlds](https://www.spigotmc.org/resources/myworlds.39594/) 插件, 安装任意一个传送插件~~
4. ~~玩家进入服务器, 背包中放一个物品, 通过传送插件传送到地狱世界, 再传送回来~~
5. ~~关闭服务器, 更换KeYi核心~~
6. ~~玩家进入服务器, 通过传送插件传送到地狱世界, 再传送回来~~
7. ~~关闭服务器, 更换purpur核心~~
8. ~~玩家进入服务器, 通过传送插件传送到地狱世界, 再传送回来 \<-- 此时背包中的物品消失了~~

这不在purpur, [Petal](https://github.com/Bloom-host/Petal)服务器中发生. 

玩家传送时出现以下错误: 
```
[09:56:53] [Server thread/ERROR]: [BKCommonLib] Failed to compile method body ([source error] dimension() not found in net.minecraft.world.level.GeneratorAccessSeed):
[09:56:53] [Server thread/ERROR]: [BKCommonLib] public void setSpawnWorld(net.minecraft.server.level.EntityPlayer instance,org.bukkit.World world) {
{
    ResourceKey key = (world == null) ? World.OVERWORLD : ((org.bukkit.craftbukkit.CraftWorld) world).getHandle().dimension();
    this.spawnDimension.set(instance, key);
}
return;}
[09:56:53] [Server thread/WARN]: [My_Worlds] Failed to load player data for NELVC
java.lang.RuntimeException: An exception occurred
Caused by: com.bergerkiller.mountiplex.dep.javassist.compiler.CompileError: dimension() not found in net.minecraft.world.level.GeneratorAccessSeed
	at com.bergerkiller.mountiplex.dep.javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:777) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.asm.javassist.MPLJvstTypeChecker.atCallExprSuppressLookup(MPLJvstTypeChecker.java:113) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.asm.javassist.MPLJvstTypeChecker.atCallExpr(MPLJvstTypeChecker.java:40) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.TypeChecker.atCondExpr(TypeChecker.java:315) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.CondExpr.accept(CondExpr.java:48) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atDeclarator(CodeGen.java:819) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Declarator.accept(Declarator.java:103) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compileMethod(Javac.java:175) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compile(Javac.java:102) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.asm.javassist.MPLCtNewMethod.make(MPLCtNewMethod.java:32) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.makeMethodAndLog(GeneratedCodeInvoker.java:45) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.create(GeneratedCodeInvoker.java:261) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker$InitGeneratedCodeInvoker.create(InitInvoker.java:320) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker.initializeInvoker(InitInvoker.java:75) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.InitInvoker$InitGeneratedCodeInvoker$mplgen44b7e504.setSpawnWorld(Unknown Source) ~[?:?]
	at com.bergerkiller.generated.net.minecraft.server.level.EntityPlayerHandle$impl.setSpawnWorld(Unknown Source) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.PlayerRespawnPoint.applyToPlayer(PlayerRespawnPoint.java:212) ~[BKCommonLib-1.19.2-v3-1410.jar:?]
	at com.bergerkiller.bukkit.mw.MWPlayerDataController.resetState(MWPlayerDataController.java:293) ~[MyWorlds多世界-1.19-v2-157.jar:?]
	at com.bergerkiller.bukkit.mw.MWPlayerDataController.refreshState(MWPlayerDataController.java:343) ~[MyWorlds多世界-1.19-v2-157.jar:?]
	at com.bergerkiller.bukkit.mw.WorldConfig.onPlayerEnter(WorldConfig.java:588) ~[MyWorlds多世界-1.19-v2-157.jar:?]
	at com.bergerkiller.bukkit.mw.MWListener.onPlayerChangedWorld(MWListener.java:317) ~[MyWorlds多世界-1.19-v2-157.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor363.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:1006) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:839) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1357) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1232) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1227) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.lambda$teleportAsync$0(CraftEntity.java:1280) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by nostalgic853** [comment]
你使用的是什么传送插件？

**Comment by ApliNi** [comment]
> 你使用的是什么传送插件？

[HuskHomes2](https://github.com/WiIIiam278/HuskHomes2)
